#!/bin/bash

# Check if venv is activated
if [ -z "$venv" ]; then
    echo "Virtual environment activating..."
    source venv/bin/activate
    echo "Starting local development server..."
fi

# Run the server
python manage.py runserver 127.0.0.1:8080
