# Generated by Django 4.1.4 on 2023-03-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_class_grade_class_session_id_class_teacher_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="grade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.grade",
            ),
        ),
    ]
