# Generated by Django 4.1.4 on 2022-12-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="students",
            name="institution",
        ),
    ]
