# Generated by Django 4.1.4 on 2023-04-30 09:37

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0016_classattendance"),
        ("core", "0002_students_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(blank=True, max_length=255)),
                ("other_names", models.CharField(blank=True, max_length=255)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=255)),
                ("id_or_passport_number", models.CharField(blank=True, max_length=255)),
                ("date_of_birth", models.DateField(blank=True)),
                ("county", models.CharField(blank=True, max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("current_address", models.TextField(blank=True)),
                ("permanent_address", models.TextField(blank=True)),
                (
                    "special_needs",
                    models.CharField(
                        blank=True, choices=[("Y", "Yes"), ("N", "No")], max_length=1
                    ),
                ),
                ("special_needs_description", models.TextField(blank=True)),
                (
                    "programme_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PGD", "Postgraduate Diploma"),
                            ("MSc", "Masters"),
                            ("PhD", "Doctorate"),
                        ],
                        max_length=3,
                    ),
                ),
                ("degree_name", models.CharField(max_length=255)),
                ("field_of_study", models.CharField(max_length=255)),
                ("faculty", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                (
                    "concept_paper",
                    models.FileField(blank=True, upload_to="concept_papers"),
                ),
                ("masters_degree_type", models.CharField(blank=True, max_length=255)),
                ("masters_degree_title", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True)),
                ("expected_completion_date", models.DateField(blank=True)),
                (
                    "mode_of_study",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FT", "Full-time"),
                            ("PT", "Part-time"),
                            ("EL", "eLearning"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "photo_1",
                    models.ImageField(blank=True, upload_to="applicant_photos"),
                ),
                (
                    "photo_2",
                    models.ImageField(blank=True, upload_to="applicant_photos"),
                ),
                ("secondary_schools_attended", models.TextField(blank=True)),
                ("university_education", models.TextField(blank=True)),
                ("other_degrees_or_diploma", models.TextField(blank=True)),
                ("research_experience", models.TextField(blank=True)),
                ("employment_work_experience", models.TextField(blank=True)),
                ("languages_spoken", models.TextField(blank=True)),
                ("referee1_name", models.CharField(blank=True, max_length=255)),
                ("referee1_designation", models.CharField(blank=True, max_length=255)),
                ("referee1_address", models.TextField(blank=True)),
                ("referee1_telephone", models.CharField(blank=True, max_length=255)),
                ("referee1_email", models.EmailField(blank=True, max_length=254)),
                ("referee2_name", models.CharField(blank=True, max_length=255)),
                ("referee2_designation", models.CharField(blank=True, max_length=255)),
                ("referee2_address", models.TextField(blank=True)),
                ("referee2_telephone", models.CharField(blank=True, max_length=255)),
                ("referee2_email", models.EmailField(blank=True, max_length=254)),
                (
                    "how_did_you_know_about_us",
                    models.CharField(blank=True, max_length=255),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="admin",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    (1, "Admin"),
                    (2, "Staff"),
                    (3, "Student"),
                    (4, "HOD"),
                    (5, "Guardian"),
                    (6, "Teacher"),
                    (7, "Specialuser"),
                    (8, "Applicant"),
                ],
                default=1,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="deputy",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.staff",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.CharField(blank=True, default="institution", max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.hod",
            ),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="bank",
            field=models.CharField(blank=True, max_length=2550),
        ),
        migrations.AlterField(
            model_name="hod",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="bank_details",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="contact_details",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="institution",
            name="currency",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="institution",
            name="examination_centre_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_location_hierarchy",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_status",
            field=models.CharField(
                choices=[(1, "Public"), (2, "Private")], default="1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_statutory_numbers",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_type",
            field=models.CharField(
                choices=[(1, "Formal"), (2, "Informal")], default="1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="staff",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="staff",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="students",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="bio_data",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="index_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="students",
            name="profile_pic",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="students",
            name="registration_number",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="relationships",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="religion",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="students",
            name="session_year_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.session",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="special_needs",
            field=models.CharField(
                choices=[
                    (1, "Physically Impaired"),
                    (2, "Visually Impaired"),
                    (3, "Hearing Impaired"),
                    (4, "Intellectually Impaired"),
                    (5, "Multiple Disabilities"),
                    (6, "Other Impairment"),
                ],
                default="1",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="sponsor_contact",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="student_contact",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="bank_account",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="bank_details",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="industrial_training_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(default="Teacher", max_length=255),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="nhif",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="pin_tax_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="secondary_bank_account",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="secondary_phone_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="social_security_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="statutory_numbers",
            field=models.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="admin_type",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.admintype",
            ),
            preserve_default=False,
        ),
    ]
