# Generated by Django 4.1.4 on 2022-12-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_admin_institution_remove_staff_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="institution",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="logo",
            field=models.FileField(default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="staff",
            name="institution",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="institution",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
    ]
