# Generated by Django 4.1.4 on 2022-12-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_admin_institution_institution_logo_staff_institution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="students",
            name="institution",
        ),
    ]
