# Generated by Django 4.1.4 on 2023-04-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_admin_admin_type_alter_admin_institution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="institution",
        ),
    ]
