# Generated by Django 4.1.4 on 2022-12-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_admin_adminhod"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdminHOD",
            new_name="Admin",
        ),
    ]
