# Generated by Django 4.1.4 on 2023-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_admin_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="bio_data",
            field=models.JSONField(blank=True),
        ),
    ]
