# Generated by Django 4.1.4 on 2022-12-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_adminhod_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
    ]
