# Generated by Django 4.1.4 on 2022-12-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_admin_institution_staff_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="desc",
            field=models.CharField(default="institution", max_length=255),
        ),
    ]
