# Generated by Django 4.1.4 on 2023-04-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_students_bio_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="bio_data",
        ),
    ]
