# Generated by Django 4.1.4 on 2022-12-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_institution_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="institution_code",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="logo",
        ),
    ]
