# Generated by Django 4.1.4 on 2022-12-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_institution_institution_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SessionYearModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_start_year", models.DateField()),
                ("session_end_year", models.DateField()),
            ],
        ),
    ]
