# Generated by Django 4.1.4 on 2022-12-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_courses_sessionyearmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="course_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.courses",
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="session_year_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.sessionyearmodel",
            ),
        ),
    ]
