# Generated by Django 4.1.4 on 2022-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_students_course_id_students_session_year_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="cost",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
