# Generated by Django 4.1.4 on 2022-12-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_courses_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
