# Generated by Django 4.1.4 on 2023-05-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_stafftype_remove_staff_institution_staff_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="staff_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.stafftype",
            ),
        ),
    ]
