# Generated by Django 4.1.4 on 2023-05-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_staff_staff_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantApprovalWorklow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("finance_approved", models.BooleanField(default=False)),
                ("department_approved", models.BooleanField(default=False)),
                ("dvc_approved", models.BooleanField(default=False)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.applicant"
                    ),
                ),
            ],
        ),
    ]
