# Generated by Django 4.1.4 on 2022-12-15 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_institution_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phonenumber", models.CharField(max_length=12)),
                ("bank", models.CharField(max_length=1000, null=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="students",
            name="guardian",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.guardian",
            ),
        ),
    ]
