# Generated by Django 4.1.4 on 2023-05-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_applicantapprovalworklow"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="application_status",
            field=models.BooleanField(default=False),
        ),
    ]
