# Generated by Django 4.1.4 on 2022-12-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_grade_institution_institution_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="fee_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
