# Generated by Django 4.1.4 on 2023-05-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_applicant_application_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HODType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="hod",
            name="hod_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.hodtype",
            ),
        ),
    ]
