# Generated by Django 4.1.4 on 2023-05-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_hodtype_hod_hod_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintype",
            name="name",
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="hodtype",
            name="name",
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
