# Generated by Django 4.1.4 on 2023-01-05 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_students_fee_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    (1, "Admin"),
                    (2, "Staff"),
                    (3, "Student"),
                    (4, "HOD"),
                    (5, "Guardian"),
                    (6, "Teacher"),
                    (7, "Specialuser"),
                ],
                default=1,
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phonenumber", models.CharField(max_length=12)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phonenumber", models.CharField(max_length=12)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HOD",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phonenumber", models.CharField(max_length=12)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
