# Generated by Django 4.1.4 on 2023-05-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_admintype_name_alter_hodtype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hod",
            name="associated_department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.department",
            ),
        ),
    ]
