# Generated by Django 4.1.4 on 2023-01-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_institution_institution_cype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institution",
            old_name="institution_cype",
            new_name="institution_type",
        ),
    ]
