# Generated by Django 4.1.4 on 2023-01-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_rename_institution_cype_institution_institution_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("1", "Preprimary"),
                    ("2", "Primary"),
                    ("3", "Secondary"),
                    ("4", "tertiary"),
                    ("5", "all"),
                ],
                default="5",
                max_length=255,
            ),
        ),
    ]
