# Generated by Django 4.1.4 on 2023-05-08 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0016_classattendance"),
        ("core", "0021_remove_students_degree_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="fee_balance",
        ),
        migrations.RemoveField(
            model_name="students",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="students",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="students",
            name="registration_type",
        ),
        migrations.RemoveField(
            model_name="students",
            name="relationships",
        ),
        migrations.RemoveField(
            model_name="students",
            name="religion",
        ),
        migrations.RemoveField(
            model_name="students",
            name="require_entry_exams",
        ),
        migrations.RemoveField(
            model_name="students",
            name="session_year_id",
        ),
        migrations.RemoveField(
            model_name="students",
            name="type_of_entry_exam",
        ),
        migrations.AddField(
            model_name="applicant",
            name="require_entry_exams",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="students",
            name="admission_number",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="students",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.course",
            ),
            preserve_default=False,
        ),
    ]
