# Generated by Django 4.1.4 on 2023-01-09 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_institution_institution_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="guardian",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="students",
                to="core.guardian",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "institution_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=30)),
                ("desc", models.CharField(default="institution", max_length=255)),
                (
                    "deputy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.staff",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.hod",
                    ),
                ),
            ],
        ),
    ]
