# Generated by Django 4.1.4 on 2023-01-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_students_guardian_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="name",
            field=models.CharField(default="yea", max_length=30),
            preserve_default=False,
        ),
    ]
