# Generated by Django 4.1.4 on 2023-05-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0016_classattendance"),
        ("core", "0022_remove_students_fee_balance_remove_students_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="academic_status",
            field=models.CharField(
                choices=[
                    ("1", "Active"),
                    ("2", "Inactive"),
                    ("3", "On-Hold"),
                    ("4", "Suspended"),
                    ("5", "Terminated"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("1", "Active"),
                    ("2", "Inactive"),
                    ("3", "On-Hold"),
                    ("4", "Suspended"),
                    ("5", "Terminated"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="boarding_type",
            field=models.CharField(
                choices=[("1", "Boarder"), ("2", "Day-Scholer")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="special_needs",
            field=models.CharField(
                choices=[
                    ("1", "Physically Impaired"),
                    ("2", "Visually Impaired"),
                    ("3", "Hearing Impaired"),
                    ("4", "Intellectually Impaired"),
                    ("5", "Multiple Disabilities"),
                    ("6", "Other Impairment"),
                ],
                default="1",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="sponsor_contact",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="sponsor_type",
            field=models.CharField(
                choices=[("1", "Government"), ("2", "Organizations"), ("3", "Sponsor")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="sponsorship_type",
            field=models.CharField(
                choices=[("1", "Self-Sponsored"), ("2", "Sponsored")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="student_contact",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="student_type",
            field=models.CharField(
                choices=[("1", "Local"), ("2", "International")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="study_type",
            field=models.CharField(
                choices=[("1", "Full Time"), ("2", "Part Time"), ("3", "Online")],
                default="1",
                max_length=10,
            ),
        ),
    ]
