# Generated by Django 4.1.4 on 2023-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_students_academic_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="concept_paper",
            field=models.FileField(blank=True, upload_to="concept_papers/"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="photo_1",
            field=models.ImageField(null=True, upload_to="applicant_photos/"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="photo_2",
            field=models.ImageField(null=True, upload_to="applicant_photos/"),
        ),
    ]
