# Generated by Django 4.1.4 on 2023-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_guardian_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guardian",
            name="name",
        ),
        migrations.AddField(
            model_name="guardian",
            name="gender",
            field=models.CharField(default="Male", max_length=50),
            preserve_default=False,
        ),
    ]
