# Generated by Django 4.1.4 on 2023-01-16 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("finance", "0003_alter_fee_session"),
        ("core", "0024_remove_guardian_name_guardian_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hod",
            name="admin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="course_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.courses",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="grade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.grade",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="session_year_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.sessionyearmodel",
            ),
        ),
        migrations.DeleteModel(
            name="Courses",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.DeleteModel(
            name="SessionYearModel",
        ),
    ]
