# Generated by Django 4.1.4 on 2023-05-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_applicant_concept_paper_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterFacultyTransferApprovalWorklow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("finance_approved", models.BooleanField(default=False)),
                ("department_approved", models.BooleanField(default=False)),
                ("dvc_approved", models.BooleanField(default=False)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.applicant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeferrmentApprovalWorklow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("admissions_approved", models.BooleanField(default=False)),
                ("dean_approved", models.BooleanField(default=False)),
                ("registrar_approved", models.BooleanField(default=False)),
                ("dvc_approved", models.BooleanField(default=False)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.applicant"
                    ),
                ),
            ],
        ),
    ]
