# Generated by Django 4.1.4 on 2023-01-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("core", "0025_alter_hod_admin_alter_students_course_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="course_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.courses",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="gender",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="profile_pic",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
