# Generated by Django 4.1.4 on 2023-02-06 11:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_class_discplinarycases_extracurricularactivities_and_more"),
        ("core", "0026_alter_students_address_alter_students_course_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="students",
            name="admission_number",
        ),
        migrations.RemoveField(
            model_name="students",
            name="guardian",
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.CharField(default="institution", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hod",
            name="contract_type",
            field=models.CharField(
                choices=[
                    (1, "Permanent"),
                    (2, "Long Term"),
                    (3, "Short Term"),
                    (4, "Contracted Labour"),
                    (5, "Probation"),
                ],
                default=5,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="bank_details",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="class_level_defaults",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="contact_details",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="currency",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="examination_centre_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_in_ASAL_area",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_location_hierarchy",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_status",
            field=models.CharField(
                choices=[(1, "Public"), (2, "Private")], default="1", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_statutory_numbers",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="logo",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="institution",
            name="registration_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="contract_type",
            field=models.CharField(
                choices=[
                    (1, "Permanent"),
                    (2, "Long Term"),
                    (3, "Short Term"),
                    (4, "Contracted Labour"),
                    (5, "Probation"),
                ],
                default=5,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="contract_years",
            field=models.CharField(default="Parmanent", max_length=255),
        ),
        migrations.AddField(
            model_name="staff",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_type",
            field=models.CharField(
                choices=[(1, "Administration"), (2, "Support")],
                default=1,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="academic_status",
            field=models.CharField(
                choices=[
                    (1, "Active"),
                    (2, "Inactive"),
                    (3, "On-Hold"),
                    (4, "Suspended"),
                    (5, "Terminated"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="account_status",
            field=models.CharField(
                choices=[
                    (1, "Active"),
                    (2, "Inactive"),
                    (3, "On-Hold"),
                    (4, "Suspended"),
                    (5, "Terminated"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="bio_data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="students",
            name="boarding_type",
            field=models.CharField(
                choices=[(1, "Boarder"), (2, "Day-Scholer")], default="1", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="extra_curricular",
            field=models.ManyToManyField(to="academics.extracurricularactivities"),
        ),
        migrations.AddField(
            model_name="students",
            name="index_number",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="students",
            name="name",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="students",
            name="registration_number",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="students",
            name="registration_type",
            field=models.CharField(
                choices=[(1, "New"), (2, "Continuing")], default="1", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="relationships",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="students",
            name="religion",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="students",
            name="require_entry_exams",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="students",
            name="require_transport",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="students",
            name="special_needs",
            field=models.CharField(
                choices=[
                    (1, "Physically Impaired"),
                    (2, "Visually Impaired"),
                    (3, "Hearing Impaired"),
                    (4, "Intellectually Impaired"),
                    (5, "Multiple Disabilities"),
                    (6, "Other Impairment"),
                ],
                default="1",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="sponsor_contact",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="students",
            name="sponsor_type",
            field=models.CharField(
                choices=[(1, "Government"), (2, "Organizations"), (3, "Sponsor")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="sponsorship_type",
            field=models.CharField(
                choices=[(1, "Self-Sponsored"), (2, "Sponsored")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="student_contact",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="students",
            name="student_type",
            field=models.CharField(
                choices=[(1, "Local"), (2, "International")], default="1", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="study_type",
            field=models.CharField(
                choices=[(1, "Full Time"), (2, "Part Time"), (3, "Online")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="type_of_entry_exam",
            field=models.CharField(
                choices=[(1, "Normal"), (2, "Special")], default="1", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="bank_details",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="contract_type",
            field=models.CharField(
                choices=[
                    (1, "Permanent"),
                    (2, "Long Term"),
                    (3, "Short Term"),
                    (4, "Contracted Labour"),
                    (5, "Probation"),
                ],
                default=5,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="statutory_numbers",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_type",
            field=models.CharField(
                choices=[(1, "Formal"), (2, "Informal")], default="1", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="gender",
            field=models.CharField(
                choices=[("1", "Male"), ("2", "Female")], default="1", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phonenumber",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
