# Generated by Django 4.1.4 on 2023-05-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_deferrmentapprovalworklow_applicant"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryWithdrawalApprovalWorklow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("admissions_approved", models.BooleanField(default=False)),
                ("dean_approved", models.BooleanField(default=False)),
                ("registrar_approved", models.BooleanField(default=False)),
                ("dvc_approved", models.BooleanField(default=False)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.students"
                    ),
                ),
            ],
        ),
    ]
