# Generated by Django 4.1.4 on 2023-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_department_desc_remove_institution_desc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="class_level_defaults",
        ),
        migrations.AddField(
            model_name="teacher",
            name="bank_account",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="industrial_training_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="nhif",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="pin_tax_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="secondary_bank_account",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="secondary_phone_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="social_security_number",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
