# Generated by Django 4.1.4 on 2023-05-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_temporarywithdrawalapprovalworklow"),
    ]

    operations = [
        migrations.AddField(
            model_name="deferrmentapprovalworklow",
            name="admissions_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="deferrmentapprovalworklow",
            name="dean_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="deferrmentapprovalworklow",
            name="dvc_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="deferrmentapprovalworklow",
            name="registrar_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="temporarywithdrawalapprovalworklow",
            name="admissions_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="temporarywithdrawalapprovalworklow",
            name="dean_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="temporarywithdrawalapprovalworklow",
            name="dvc_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="temporarywithdrawalapprovalworklow",
            name="registrar_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
