# Generated by Django 4.1.4 on 2023-02-13 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_institution_class_level_defaults_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="institution_accomodation_type",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_category",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_cluster",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_gender_category",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_order",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_residence",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
