# Generated by Django 4.1.4 on 2023-03-13 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_institution_institution_accomodation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardian",
            name="admin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
