# Generated by Django 4.1.4 on 2023-03-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_guardian_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="students",
            name="extra_curricular",
        ),
    ]
