# Generated by Django 4.1.4 on 2023-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_students_academic_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interfacultytransferapprovalworklow",
            old_name="department_approved",
            new_name="admissions_approved",
        ),
        migrations.RenameField(
            model_name="interfacultytransferapprovalworklow",
            old_name="finance_approved",
            new_name="dean_approved",
        ),
        migrations.RemoveField(
            model_name="interfacultytransferapprovalworklow",
            name="applicant",
        ),
        migrations.AddField(
            model_name="interfacultytransferapprovalworklow",
            name="admissions_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="interfacultytransferapprovalworklow",
            name="dean_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="interfacultytransferapprovalworklow",
            name="dvc_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="interfacultytransferapprovalworklow",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="interfacultytransferapprovalworklow",
            name="registrar_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interfacultytransferapprovalworklow",
            name="registrar_comments",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="students",
            name="academic_status",
            field=models.CharField(
                choices=[
                    (1, "Active"),
                    (2, "Inactive"),
                    (3, "On-Hold"),
                    (4, "Suspended"),
                    (5, "Terminated"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="account_status",
            field=models.CharField(
                choices=[
                    (1, "Active"),
                    (2, "Inactive"),
                    (3, "On-Hold"),
                    (4, "Suspended"),
                    (5, "Terminated"),
                ],
                default="1",
                max_length=10,
            ),
        ),
    ]
