# Generated by Django 4.1.4 on 2023-05-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0016_classattendance"),
        (
            "core",
            "0032_rename_department_approved_interfacultytransferapprovalworklow_admissions_approved_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interfacultytransferapprovalworklow",
            name="current_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="current_course_approvals",
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="interfacultytransferapprovalworklow",
            name="desired_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="desired_course_approvals",
                to="academics.course",
            ),
        ),
    ]
