# Generated by Django 4.1.4 on 2023-05-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_interfacultytransferapprovalworklow_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="academic_status",
            field=models.CharField(
                choices=[
                    ("1", "Active"),
                    ("2", "Inactive"),
                    ("3", "On-Hold"),
                    ("4", "Suspended"),
                    ("5", "Terminated"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("1", "Active"),
                    ("2", "Inactive"),
                    ("3", "On-Hold"),
                    ("4", "Suspended"),
                    ("5", "Terminated"),
                ],
                default="1",
                max_length=10,
            ),
        ),
    ]
