# Generated by Django 4.1.4 on 2023-05-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_students_academic_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="hod",
            name="institution",
        ),
        migrations.AddField(
            model_name="customuser",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.institution",
            ),
        ),
    ]
