# Generated by Django 4.1.4 on 2023-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_remove_admin_institution_remove_hod_institution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="institution_location_hierarchy",
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
