# Generated by Django 4.1.4 on 2023-06-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_institution_institution_location_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.department",
            ),
        ),
    ]
