# Generated by Django 4.1.4 on 2023-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_students_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cooldown_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
