# Generated by Django 4.1.4 on 2023-06-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_customuser_cooldown_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.FileField(null=True, upload_to="media/"),
        ),
    ]
