# Generated by Django 4.1.4 on 2023-06-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_department_department_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
