# Generated by Django 4.1.4 on 2023-06-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_institution_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("Suspended", "Suspended"),
                    ("Deactivated", "Deactivated"),
                    ("Active", "Active"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
