# Generated by Django 4.1.4 on 2023-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_customuser_account_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("Suspended", "Suspended"),
                    ("Deactivated", "Deactivated"),
                    ("Activation Requested", "Activation Requested"),
                    ("Active", "Active"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
