# Generated by Django 4.1.4 on 2023-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_customuser_account_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
