# Generated by Django 4.1.4 on 2023-07-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_department_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["id"]},
        ),
    ]
