# Generated by Django 4.1.4 on 2023-07-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_department_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={},
        ),
        migrations.AddField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
