# Generated by Django 4.1.4 on 2023-07-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="profile_pic",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
