# Generated by Django 4.1.4 on 2023-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_campus_department_code_department_gl_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="status",
            field=models.CharField(
                choices=[(1, "Active"), (2, "Inactive")], default="1", max_length=255
            ),
        ),
    ]
