# Generated by Django 4.1.4 on 2023-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_school_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                ("campus", models.CharField(max_length=100)),
            ],
        ),
    ]
