# Generated by Django 4.1.4 on 2023-09-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="campus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.campus",
            ),
        ),
    ]
