# Generated by Django 4.1.4 on 2023-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_alter_house_campus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="code",
            field=models.CharField(max_length=100),
        ),
    ]
