# Generated by Django 4.1.4 on 2023-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_house_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=30, null=True)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=30)),
                ("service_unit_of_measure", models.CharField(max_length=30)),
                ("rate", models.CharField(max_length=30)),
                ("payment_plan", models.CharField(max_length=30)),
                ("taxable", models.CharField(max_length=30)),
                ("tax_rate", models.CharField(max_length=30)),
                ("gl_account", models.CharField(max_length=30)),
                ("notes", models.TextField(null=True)),
            ],
        ),
    ]
