# Generated by Django 4.1.4 on 2023-09-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_ecactivities"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=100)),
                ("job_type", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("gl_account", models.CharField(max_length=100)),
                ("notes", models.TextField(null=True)),
            ],
        ),
    ]
