# Generated by Django 4.1.4 on 2023-09-15 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_bank_paymentmethods"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("occurrence", models.CharField(max_length=100)),
                ("applicability", models.CharField(max_length=100)),
                (
                    "priority",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                ("default_amount", models.CharField(max_length=100)),
                ("required_percentage", models.CharField(max_length=100)),
                ("on_hold_disable_posting_on_item", models.CharField(max_length=100)),
                ("gl_account", models.CharField(max_length=100)),
                ("gl_statement_prefix", models.CharField(max_length=100)),
                ("notes", models.TextField(null=True)),
            ],
        ),
    ]
