# Generated by Django 4.1.4 on 2023-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_feeitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("faculty_or_school", models.CharField(max_length=100)),
                ("program", models.CharField(max_length=100)),
                ("system", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("class_name", models.CharField(max_length=100)),
                ("sponsorship_type", models.CharField(max_length=100)),
                ("year_of_study", models.CharField(max_length=100)),
                ("fee_item", models.CharField(max_length=100)),
                (
                    "fee_item_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("gl_statement_prefix", models.CharField(max_length=100)),
                ("notes", models.TextField(null=True)),
            ],
        ),
    ]
