# Generated by Django 4.1.4 on 2023-09-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0028_delete_discplinarycases"),
        ("core", "0062_billingtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingtemplate",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="billingtemplate",
            name="faculty_or_school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.school",
            ),
        ),
        migrations.AlterField(
            model_name="billingtemplate",
            name="fee_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.feeitem",
            ),
        ),
        migrations.AlterField(
            model_name="billingtemplate",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.program",
            ),
        ),
        migrations.AlterField(
            model_name="billingtemplate",
            name="system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.curriculumsystem",
            ),
        ),
    ]
