# Generated by Django 4.1.4 on 2024-02-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_alter_billingtemplate_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dormitory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Co-Ed", "Co-Ed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("bed_capacity", models.IntegerField()),
                ("occupied", models.IntegerField(default=0)),
                ("damaged", models.IntegerField(default=0)),
                ("damaged_remarks", models.TextField(blank=True)),
                ("available", models.IntegerField(default=0)),
                ("min_percentage_warning", models.FloatField(default=10.0)),
                ("sections", models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name="house",
            name="current_capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="house",
            name="maximum_capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("bed_capacity", models.IntegerField()),
                ("occupied", models.IntegerField(default=0)),
                ("damaged", models.IntegerField(default=0)),
                ("damaged_remarks", models.TextField(blank=True)),
                ("available", models.IntegerField(default=0)),
                ("cubicles", models.IntegerField(default=1)),
                (
                    "dormitory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.dormitory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cubicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_capacity", models.IntegerField()),
                ("cubicles", models.IntegerField(default=1)),
                ("occupied", models.IntegerField(default=0)),
                ("damaged", models.IntegerField(default=0)),
                ("damaged_remarks", models.TextField(blank=True)),
                ("available", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.section"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField(auto_now_add=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.house"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.students"
                    ),
                ),
            ],
        ),
    ]
