# Generated by Django 4.1.4 on 2024-02-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0028_delete_discplinarycases"),
        ("core", "0064_dormitory_house_current_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.session",
            ),
        ),
    ]
