# Generated by Django 4.1.4 on 2024-02-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_booking_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="dormitory",
        ),
        migrations.DeleteModel(
            name="Cubicle",
        ),
        migrations.DeleteModel(
            name="Dormitory",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]
