# Generated by Django 4.1.4 on 2024-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_remove_section_dormitory_delete_cubicle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
