# Generated by Django 4.1.4 on 2024-02-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_house_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="booked_hostel",
            field=models.BooleanField(default=False),
        ),
    ]
