# Generated by Django 4.1.4 on 2024-02-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_students_booked_hostel"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
