# Generated by Django 4.1.4 on 2024-02-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.school",
            ),
        ),
        migrations.CreateModel(
            name="InterSchoolTransferApprovalWorklow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("admissions_approved", models.BooleanField(default=False)),
                ("admissions_comments", models.CharField(blank=True, max_length=255)),
                ("dean_approved", models.BooleanField(default=False)),
                ("dean_comments", models.CharField(blank=True, max_length=255)),
                ("registrar_approved", models.BooleanField(default=False)),
                ("registrar_comments", models.CharField(blank=True, max_length=255)),
                ("dvc_approved", models.BooleanField(default=False)),
                ("dvc_comments", models.CharField(blank=True, max_length=255)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.students"
                    ),
                ),
            ],
        ),
    ]
