# Generated by Django 4.1.4 on 2024-02-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_students_school_interschooltransferapprovalworklow"),
    ]

    operations = [
        migrations.AddField(
            model_name="interschooltransferapprovalworklow",
            name="current_school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="current_school_approvals",
                to="core.school",
            ),
        ),
        migrations.AddField(
            model_name="interschooltransferapprovalworklow",
            name="desired_school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="desired_school_approvals",
                to="core.school",
            ),
        ),
    ]
