# Generated by Django 4.1.4 on 2024-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_interschooltransferapprovalworklow_current_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="admissions_comments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="dean_approved",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="dean_comments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="dvc_approved",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="dvc_comments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="registrar_approved",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="registrar_comments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
