# Generated by Django 4.1.4 on 2024-02-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0028_delete_discplinarycases"),
        (
            "core",
            "0072_alter_interfacultytransferapprovalworklow_admissions_comments_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingtemplate",
            name="course",
        ),
        migrations.RemoveField(
            model_name="billingtemplate",
            name="faculty_or_school",
        ),
        migrations.RemoveField(
            model_name="billingtemplate",
            name="fee_item",
        ),
        migrations.RemoveField(
            model_name="billingtemplate",
            name="program",
        ),
        migrations.RemoveField(
            model_name="billingtemplate",
            name="system",
        ),
        migrations.RemoveField(
            model_name="paymentmethods",
            name="default_bank_account",
        ),
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="current_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="current_course_approvals",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="interfacultytransferapprovalworklow",
            name="desired_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="desired_course_approvals",
                to="academics.course",
            ),
        ),
        migrations.DeleteModel(
            name="Bank",
        ),
        migrations.DeleteModel(
            name="BillingTemplate",
        ),
        migrations.DeleteModel(
            name="FeeItem",
        ),
        migrations.DeleteModel(
            name="PaymentMethods",
        ),
    ]
