# Generated by Django 4.1.4 on 2022-12-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0014_guardian_students_guardian"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("payment", "fee_payment"),
                            ("fee_charge", "fee_charge"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=255,
                    ),
                ),
                ("form_of_payment", models.CharField(max_length=1000, null=True)),
                ("ammount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "guardian",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.students"
                    ),
                ),
            ],
        ),
    ]
