# Generated by Django 4.1.4 on 2024-02-25 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0073_remove_billingtemplate_course_and_more"),
        ("academics", "0028_delete_discplinarycases"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bank_code", models.CharField(max_length=10)),
                ("bank_name", models.CharField(max_length=100)),
                ("branch_code", models.CharField(max_length=10)),
                ("branch_name", models.CharField(max_length=100)),
                ("physical_address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BillingItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=100)),
                ("is_fee", models.BooleanField(default=False)),
                ("category", models.CharField(max_length=100)),
                ("occurrence", models.CharField(max_length=100)),
                ("applicability", models.JSONField(null=True)),
                (
                    "priority",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                ("default_amount", models.CharField(max_length=100)),
                ("required_percentage", models.CharField(max_length=100)),
                ("on_hold_disable_posting_on_item", models.CharField(max_length=100)),
                ("gl_account", models.CharField(max_length=100)),
                ("gl_statement_prefix", models.CharField(max_length=100)),
                ("notes", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transactiontype",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_code", models.CharField(max_length=255)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("form_of_payment", models.CharField(max_length=255)),
                ("ammount_paid", models.DecimalField(decimal_places=2, max_digits=20)),
                ("date", models.DateTimeField(auto_now=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("Payee", models.CharField(max_length=255, null=True)),
                ("Payer", models.CharField(max_length=255, null=True)),
                ("comments", models.CharField(max_length=255, null=True)),
                (
                    "other_resources",
                    models.FileField(blank=True, upload_to="media/account_files"),
                ),
                (
                    "receipt_image",
                    models.ImageField(blank=True, upload_to="media/transaction_images"),
                ),
                (
                    "associated_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="finance.transactiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethods",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("transaction_reference_required", models.CharField(max_length=100)),
                ("unit_of_measure_required", models.CharField(max_length=100)),
                ("on_hold_disable_posting_on_item", models.CharField(max_length=100)),
                ("gl_account", models.CharField(max_length=100)),
                ("notes", models.TextField(null=True)),
                (
                    "default_bank_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="finance.bank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("ammount", models.IntegerField()),
                ("is_recurrent", models.BooleanField(default=False)),
                ("billed", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=100)),
                ("sponsorship_type", models.CharField(max_length=100)),
                ("year_of_study", models.CharField(max_length=100)),
                (
                    "fee_item_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("gl_statement_prefix", models.CharField(max_length=100)),
                ("notes", models.TextField(null=True)),
                (
                    "billing_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="finance.billingitem",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="academics.course",
                    ),
                ),
                (
                    "faculty_or_school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.school",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.program",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.curriculumsystem",
                    ),
                ),
            ],
        ),
    ]
