# Generated by Django 4.1.4 on 2023-03-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_students_grade"),
        ("academics", "0004_class_grade_class_session_id_class_teacher_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("payment", "fee_payment"),
                            ("charge", "fee_charge"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=255,
                    ),
                ),
                (
                    "form_of_payment",
                    models.CharField(
                        choices=[
                            ("mobile_money", "mobile_money"),
                            ("bank", "bank"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=255,
                    ),
                ),
                ("ammount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("ammount", models.IntegerField()),
                ("is_recurrent", models.BooleanField(default=False)),
                ("billed", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.session",
                    ),
                ),
            ],
        ),
    ]
