# Generated by Django 4.1.4 on 2023-05-03 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactiontype",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="student",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="associated_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="ammount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="form_of_payment",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="finance.transactiontype",
            ),
            preserve_default=False,
        ),
    ]
