# Generated by Django 4.1.4 on 2023-01-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_customuser_user_type_teacher_specialuser_hod"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="guardian",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="form_of_payment",
            field=models.CharField(
                choices=[
                    ("mobile_money", "mobile_money"),
                    ("bank", "bank"),
                    ("other", "other"),
                ],
                default="other",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.students",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("payment", "fee_payment"),
                    ("charge", "fee_charge"),
                    ("other", "other"),
                ],
                default="other",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("ammount", models.IntegerField()),
                ("is_recurrent", models.BooleanField(default=False)),
                ("billed", models.BooleanField(default=False)),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.admin"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.sessionyearmodel",
                    ),
                ),
            ],
        ),
    ]
