# Generated by Django 4.1.4 on 2024-02-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingtemplate",
            name="billing_item",
        ),
    ]
