# Generated by Django 4.1.4 on 2023-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_transactiontype_remove_transaction_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
