# Generated by Django 4.1.4 on 2023-01-16 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("finance", "0002_remove_transaction_guardian_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.sessionyearmodel",
            ),
        ),
    ]
