# Generated by Django 4.1.4 on 2023-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_transaction_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_code",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
