# Generated by Django 4.1.4 on 2023-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_transaction_payee_transaction_payer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="other_resources",
            field=models.FileField(blank=True, upload_to="account_files"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receipt_image",
            field=models.ImageField(blank=True, upload_to="transaction_images"),
        ),
    ]
