# Generated by Django 4.1.4 on 2023-06-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_transaction_other_resources_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="other_resources",
            field=models.FileField(blank=True, upload_to="media/account_files"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receipt_image",
            field=models.ImageField(blank=True, upload_to="media/transaction_images"),
        ),
    ]
