# Generated by Django 4.1.4 on 2023-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("class_capacity", models.CharField(max_length=100)),
                ("streams_per_lass", models.CharField(max_length=100)),
                ("exam_data", models.JSONField()),
                ("lecturer_max_subject", models.CharField(max_length=100)),
                ("student_teacher_ratio", models.CharField(max_length=100)),
                ("curriculum_description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DiscplinaryCases",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("displinary_action", models.CharField(max_length=255)),
                ("discplinary_case_notes", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("resumption_date", models.DateTimeField()),
                ("notes", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ExtraCurricularActivities",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("notes", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="sessionyearmodel",
            old_name="session_end_year",
            new_name="session_end_date",
        ),
        migrations.RenameField(
            model_name="sessionyearmodel",
            old_name="session_start_year",
            new_name="session_start_date",
        ),
    ]
