# Generated by Django 4.1.4 on 2023-03-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.students"
            ),
        ),
        migrations.AddField(
            model_name="classenrollment",
            name="selected_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="academics.class"
            ),
        ),
        migrations.AddField(
            model_name="classenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.students"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="grade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.grade",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.teacher",
            ),
        ),
    ]
