# Generated by Django 4.1.4 on 2023-03-13 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_guardian_admin"),
        ("academics", "0002_class_discplinarycases_extracurricularactivities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enrollment_id", models.AutoField(primary_key=True, serialize=False)),
                ("enrollment_date", models.DateField(auto_now=True)),
                (
                    "enrolled_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="academics.class",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.students",
                    ),
                ),
            ],
        ),
    ]
