# Generated by Django 4.1.4 on 2023-03-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_fee_session"),
        ("core", "0030_alter_guardian_admin"),
        ("academics", "0003_enrollment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SessionYearModel",
            new_name="Session",
        ),
        migrations.RenameField(
            model_name="enrollment",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RemoveField(
            model_name="class",
            name="class_capacity",
        ),
        migrations.RemoveField(
            model_name="class",
            name="curriculum_description",
        ),
        migrations.RemoveField(
            model_name="class",
            name="exam_data",
        ),
        migrations.RemoveField(
            model_name="class",
            name="lecturer_max_subject",
        ),
        migrations.RemoveField(
            model_name="class",
            name="streams_per_lass",
        ),
        migrations.RemoveField(
            model_name="class",
            name="student_teacher_ratio",
        ),
        migrations.AddField(
            model_name="class",
            name="course_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="course_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="is_elective",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="class",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="extracurricularactivities",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="extracurricularactivities",
            name="notes",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_name",
            field=models.CharField(max_length=50),
        ),
    ]
