# Generated by Django 4.1.4 on 2023-03-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("academics", "0003_remove_class_grade_remove_class_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="grade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.grade",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="session_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.session",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.teacher",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.students",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grade",
            name="grade_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
