# Generated by Django 4.1.4 on 2023-03-13 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_rename_sessionyearmodel_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="session_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.session",
            ),
        ),
    ]
