# Generated by Django 4.1.4 on 2023-03-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_students_grade"),
        ("academics", "0004_class_grade_class_session_id_class_teacher_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Grade",
            new_name="GradeLevel",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("session", "student")},
        ),
    ]
