# Generated by Django 4.1.4 on 2023-03-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_class_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="grade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.grade",
            ),
        ),
    ]
