# Generated by Django 4.1.4 on 2023-03-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_rename_grade_gradelevel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="grade",
        ),
        migrations.AddField(
            model_name="class",
            name="gradelevel",
            field=models.ManyToManyField(to="academics.gradelevel"),
        ),
        migrations.CreateModel(
            name="ClusterClass",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cluster_class_name", models.CharField(max_length=100)),
                ("classes", models.ManyToManyField(to="academics.class")),
            ],
        ),
        migrations.AlterField(
            model_name="gradelevel",
            name="compulsory_classes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.clusterclass"
            ),
        ),
    ]
