# Generated by Django 4.1.4 on 2023-03-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_remove_class_grade_class_gradelevel_clusterclass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="gradelevel",
            field=models.ManyToManyField(blank=True, to="academics.gradelevel"),
        ),
        migrations.AlterField(
            model_name="clusterclass",
            name="classes",
            field=models.ManyToManyField(blank=True, to="academics.class"),
        ),
    ]
