# Generated by Django 4.1.4 on 2023-03-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_remove_students_course_id_and_more"),
        ("academics", "0006_class_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Courses",
        ),
        migrations.DeleteModel(
            name="ExtraCurricularActivities",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="enrolled_class",
        ),
        migrations.AddField(
            model_name="class",
            name="cost",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.session",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grade",
            name="compulsory_classes",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classenrollment",
            name="selected_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="academics.class"
            ),
        ),
        migrations.AddField(
            model_name="classenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.students"
            ),
        ),
    ]
