# Generated by Django 4.1.4 on 2023-04-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_class_gradelevel_alter_clusterclass_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterclass",
            name="classes",
            field=models.ManyToManyField(to="academics.class"),
        ),
    ]
