# Generated by Django 4.1.4 on 2023-03-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_classenrollment_delete_courses_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="class",
            old_name="course_code",
            new_name="class_code",
        ),
        migrations.RenameField(
            model_name="class",
            old_name="course_name",
            new_name="class_name",
        ),
    ]
