# Generated by Django 4.1.4 on 2023-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_alter_clusterclass_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterclass",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
