# Generated by Django 4.1.4 on 2023-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_alter_clusterclass_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="gradelevel",
            field=models.ManyToManyField(to="academics.gradelevel"),
        ),
    ]
