# Generated by Django 4.1.4 on 2023-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_alter_class_gradelevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
