# Generated by Django 4.1.4 on 2023-04-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_students_grade"),
        ("academics", "0012_rename_enrollment_id_enrollment_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("exam_date", models.DateTimeField()),
                ("is_compulsory", models.BooleanField(default=True)),
                (
                    "exam_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transcripts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_results", models.JSONField(null=True)),
                ("score", models.FloatField()),
                ("grade", models.CharField(max_length=255)),
                ("passed", models.BooleanField(default=False)),
                ("remarks", models.TextField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.exam"
                    ),
                ),
                (
                    "sessions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="academics.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.students"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeRange",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=1,
                    ),
                ),
                ("min_score", models.IntegerField()),
                ("max_score", models.IntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_ranges",
                        to="academics.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grade", models.CharField(max_length=1)),
                ("score", models.IntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.exam"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.students"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamRegistration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_registered", models.DateTimeField(auto_now=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "exams",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.exam"
                    ),
                ),
                ("student", models.ManyToManyField(to="core.students")),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.examtype"
            ),
        ),
    ]
