# Generated by Django 4.1.4 on 2023-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0013_exam_examtype_transcripts_graderange_examresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examregistration",
            name="registered",
            field=models.BooleanField(default=False),
        ),
    ]
