# Generated by Django 4.1.4 on 2023-04-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_students_grade"),
        ("academics", "0014_examregistration_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examregistration",
            name="exams",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.exam",
            ),
        ),
        migrations.RemoveField(
            model_name="examregistration",
            name="student",
        ),
        migrations.AddField(
            model_name="examregistration",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.students",
            ),
        ),
    ]
