# Generated by Django 4.1.4 on 2023-04-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_students_grade"),
        ("academics", "0015_alter_examregistration_exams_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAttendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField()),
                (
                    "absent",
                    models.ManyToManyField(
                        blank=True, related_name="absentees", to="core.students"
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.class",
                    ),
                ),
                ("present", models.ManyToManyField(blank=True, to="core.students")),
            ],
        ),
    ]
