# Generated by Django 4.1.4 on 2023-06-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0017_academiccommunication"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AcademicCommunication",
            new_name="AcademicCommunications",
        ),
    ]
