# Generated by Django 4.1.4 on 2023-07-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0019_course_compulsory_classes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["id"]},
        ),
    ]
