# Generated by Django 4.1.4 on 2023-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0020_alter_session_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
