# Generated by Django 4.1.4 on 2023-07-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0021_course_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"]},
        ),
    ]
