# Generated by Django 4.1.4 on 2023-09-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0022_alter_course_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradelevel",
            name="cost",
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="assigned_class_capacity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="class_capacity",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="class_progression_mean_grade_score",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="notes",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="number_of_streams",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="program",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="students_teacher_ratio",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="system",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gradelevel",
            name="compulsory_classes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.clusterclass",
            ),
        ),
    ]
