# Generated by Django 4.1.4 on 2023-09-08 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_school_status"),
        ("academics", "0023_remove_gradelevel_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradelevel",
            name="system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.curriculumsystem",
            ),
        ),
    ]
