# Generated by Django 4.1.4 on 2023-09-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_school_status"),
        ("academics", "0024_alter_gradelevel_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyProgression",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("program", models.CharField(max_length=50)),
                ("number_of_progression_steps", models.IntegerField()),
                ("step", models.CharField(max_length=50)),
                ("class_code", models.CharField(max_length=50)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="academics.course",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.curriculumsystem",
                    ),
                ),
            ],
        ),
    ]
