# Generated by Django 4.1.4 on 2023-09-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_school_status"),
        ("academics", "0025_studyprogression"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudyProgression",
            new_name="ClassProgression",
        ),
    ]
