# Generated by Django 4.1.4 on 2023-09-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_school_status"),
        ("academics", "0026_rename_studyprogression_classprogression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classprogression",
            name="class_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="classprogression",
            name="code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="classprogression",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="classprogression",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="classprogression",
            name="number_of_progression_steps",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="classprogression",
            name="program",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="classprogression",
            name="step",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="classprogression",
            name="system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.curriculumsystem",
            ),
        ),
    ]
