# Generated by Django 4.1.4 on 2023-09-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0027_alter_classprogression_class_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscplinaryCases",
        ),
    ]
